#if !canImport(ObjectiveC)
import XCTest

extension OneDriveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OneDriveTests = [
        ("testFile", testFile),
        ("testFolder", testFolder),
        ("testGetToken", testGetToken),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OneDriveTests.__allTests__OneDriveTests),
    ]
}
#endif
